# Generated by Django 4.0.6 on 2022-12-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_user1_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='yBuNwAMAcDFhKhJgQgkU', max_length=50),
        ),
    ]
