# Generated by Django 4.0.6 on 2022-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_user1_passphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(default='NA', max_length=20)),
                ('symbol', models.CharField(default='NA', max_length=20)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('price_in', models.FloatField(default=0)),
                ('side', models.CharField(default='NA', max_length=20)),
                ('current_price', models.FloatField(default=0)),
                ('time_out', models.DateTimeField(default=0)),
                ('price_out', models.FloatField(default=0)),
                ('status', models.CharField(default='NA', max_length=20)),
                ('token', models.CharField(default='NA', max_length=20)),
                ('pnl', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='positions_userwise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NA', max_length=20)),
                ('strategy_name', models.CharField(default='NA', max_length=20)),
                ('symbol', models.CharField(default='NA', max_length=20)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('price_in', models.FloatField(default=0)),
                ('side', models.CharField(default='NA', max_length=20)),
                ('current_price', models.FloatField(default=0)),
                ('time_out', models.DateTimeField(default=0)),
                ('price_out', models.FloatField(default=0)),
                ('status', models.CharField(default='NA', max_length=20)),
                ('token', models.CharField(default='NA', max_length=20)),
                ('pnl', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NA', max_length=20)),
                ('strategy_name', models.CharField(default='NA', max_length=20)),
                ('symbols', models.CharField(default='[]', max_length=20)),
                ('status', models.CharField(default='off', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BOT',
        ),
        migrations.DeleteModel(
            name='BOT1',
        ),
        migrations.DeleteModel(
            name='BOT2',
        ),
        migrations.DeleteModel(
            name='BOT3',
        ),
        migrations.DeleteModel(
            name='BOT4',
        ),
        migrations.DeleteModel(
            name='dashboard_analysis',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.DeleteModel(
            name='tradingview_orders',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='Max_drawdown',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='alpaca_api_keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='alpaca_base_url',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='alpaca_secret_keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='binance_API_keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='binance_Secret_Keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='free',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='kucoin_api_keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='kucoin_password',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='kucoin_secret_keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_DOB',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_api_appname',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_api_appsource',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_api_encryptkey',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_api_password',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_api_userid',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_api_userkey',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_email',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='paisa_password',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='passphrase',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='symbols_used',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='winning',
        ),
        migrations.AddField(
            model_name='user1',
            name='angel_token',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='angel_api_keys',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='angel_client_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='angel_password',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='fullname',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
