# Generated by Django 4.0.6 on 2023-01-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_subscriptions_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_main', models.CharField(default='admin', max_length=10)),
                ('admin_api_keys', models.CharField(default='NA', max_length=10)),
                ('admin_client_id', models.CharField(default='NA', max_length=100)),
                ('admin_password', models.CharField(default='NA', max_length=100)),
                ('admin_token', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(default='NA', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='positions',
            name='stoploss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='positions',
            name='strategy1_status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='positions',
            name='takeprofit_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='positions',
            name='takeprofit_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='positions_userwise',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
