# Generated by Django 4.0.6 on 2023-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_admin_info_strategy_positions_stoploss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_info',
            name='expirydate',
            field=models.CharField(default='DDMMMYY', max_length=100),
        ),
    ]
