# Generated by Django 4.0.6 on 2023-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_admin_info_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='strategy_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='symbols',
            field=models.CharField(default='', max_length=20),
        ),
    ]
