# Generated by Django 4.0.6 on 2023-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_subscriptions_strategy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='symbols',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
