# Generated by Django 4.0.6 on 2023-01-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_subscriptions_symbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='symbols',
            field=models.CharField(default='NA', max_length=2000),
        ),
    ]
