# Generated by Django 4.0.6 on 2023-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_subscriptions_symbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
