# Generated by Django 4.0.6 on 2023-01-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_subscriptions_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='strategy_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='positions_userwise',
            name='strategy_name',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
