# Generated by Django 4.0.6 on 2023-01-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_positions_strategy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='strategy1_status',
            field=models.CharField(default='OPEN', max_length=100),
        ),
    ]
